### ISSUE TITLE
Орфографічні помилки

### ISSUE THREAD

**Issue by arysin** [keedhost/sublime-text-3-uk_UA#1]
Викоритовувати 3
Викорисовувати 1
Двиділити 1
Нет 1
Сніппети 1 (загальні запозичені назви подвоєння не зберігають)
столбців 5
символов 5
стврення 3
файла 2
столбця 2
курсра 1
тега 1
срядкам 1
відступа 1
відволіченний 1
макроса 1
сніппет 1
проекта 1

**Comment by keedhost** [comment]
Дуже дякую, виправив!

**Comment by arysin** [comment]
І вам дякую! Можливо стане у пригоді:
1) загнати все в один файл
2) запустити скрипт https://github.com/brown-uk/dict_uk/blob/master/src/tools/groovy/spell/Spell.groovy -i <мійфайл.txt>
3) на виході буде три файли <мійфайл.....txt> зі словами не знайденими в орфографічному словнику
